#!/bin/bash
# Copyright (C) 2018 Stephen Broccardo

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


function build_control_ac_inp {
	# build a control.inp by concatenating the various sections
	#
	# $1 is the scenario
	# $2 is the path to the control_ac.inp that we are generating
	# $3 is the single-scattering albedo ssa090 or ssa100

	if [ -f $SCENARIO_DIR/$1/$3/control_ac.d/001scattering_mode ] ; then
		SCATTERING_MODE=$SCENARIO_DIR/$1/$3/control_ac.d/001scattering_mode
	else SCATTERING_MODE=$SCENARIO_DIR/control_ac.d/001scattering_mode ; fi

	if [ -f $SCENARIO_DIR/$1/$3/control_ac.d/002sublayers ] ; then
		SUBLAYERS=$SCENARIO_DIR/$1/$3/control_ac.d/002sublayers
	else SUBLAYERS=$SCENARIO_DIR/control_ac.d/002sublayers ; fi

	if [ -f $SCENARIO_DIR/$1/$3.d/003adaptive_grid ] ; then 
	 	ADAPTIVE_GRID=$SCENARIO_DIR/$1/$3.d/003adaptive_grid
	else ADAPTIVE_GRID=$SCENARIO_DIR/control_ac.d/003adaptive_grid ; fi

	echo "Using the following for control_ac.inp:"
	echo $SCATTERING_MODE
	echo $SUBLAYERS
	echo $ADAPTIVE_GRID

	cat $SCATTERING_MODE $SUBLAYERS $ADAPTIVE_GRID > $2
}
