#!/bin/bash
# Copyright (C) 2018 Stephen Broccardo

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function build_man_aer_inp {
	# build a man_aer.inp by concatenating the various sections
	#
	# $1 is the scenario
	# $2 is the path to the man_aer.inp that we wish to build
	# $3 is the single-scattering albedo as percent (eg: ssa100 or ssa090)

	if [ -f $SCENARIO_DIR/$1/$3.d/001scattering_mode ] ; then
		SCATTERING_MODE=$SCENARIO_DIR/$1/$3.d/001phase_function
	else SCATTERING_MODE=$SCENARIO_DIR/man_aer.d/001phase_function ; fi

	if [ -f $SCENARIO_DIR/$1/$3.d/002extinction_coeff ] ; then
		SUBLAYERS=$SCENARIO_DIR/$1/$3.d/002extinction_coeff
	else SUBLAYERS=$SCENARIO_DIR/man_aer.d/002extinction_coeff ; fi

	if [ -f $SCENARIO_DIR/$1/$3.d/003absorption_coeff ] ; then 
	 	ADAPTIVE_GRID=$SCENARIO_DIR/$1/$3.d/003absorption_coeff
	else ADAPTIVE_GRID=$SCENARIO_DIR/man_aer.d/003absorption_coeff ; fi

	echo "Using the following for man_aer.inp:"
	echo $SCATTERING_MODE
	echo $SUBLAYERS
	echo $ADAPTIVE_GRID


	cat $SCATTERING_MODE $SUBLAYERS $ADAPTIVE_GRID > $2
}
