#!/bin/bash
# Copyright (C) 2018 Stephen Broccardo

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function build_control_geom_inp {
	# build a control_geom.inp by concatenating the various sections
	#
	# $1 is the scenario
	# $2 is the path to control_geom.inp that we wish to build
	# $3 chooses between amf and block_amf

	if [ -f $SCENARIO_DIR/$1/$3/control_geom.d/001control_geom ] ; then
		CONTROL_GEOM=$SCENARIO_DIR/$1/$3/control_geom.d/001control_geom
	else CONTROL_GEOM=$SCENARIO_DIR/control_geom.d/001control_geom ; fi

	echo "Using the following for control_geom.inp:"
	echo $CONTROL_GEOM

	cat $CONTROL_GEOM > $2
}
